# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69c932ebe5803a15fd91db1b34bc8a16b2b45bd8da1c1226237fec36611ecd28cca59477ef0eba3ecdba4ac4903663e4d1d755001f3469db695595600167729

test:
  secret_key_base: 455f23b870d1e147b1f1652820251b2944acc81837e47fa62c4dcd132f9bf7d33f532f21baace8193f61f310d40f2432aa16be1158f2ec8f78e8b254d3d7671e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
